In [1]:
import pandas as pd
import sklearn as skl
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
wine_df = pd.read_csv("preprocessed_wine_data.csv", sep=",")
wine_df.head(20)

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0             7.5              0.33         0.32           11.10      0.036   
1             6.3              0.27         0.29           12.20      0.044   
2             7.0              0.30         0.51           13.60      0.050   
3             7.4              0.38         0.27            7.50      0.041   
4             8.1              0.12         0.38            0.90      0.034   
5             6.6              0.20         0.38            7.90      0.052   
6             7.3              0.26         0.36            5.20      0.040   
7             6.9              0.32         0.17            7.60      0.042   
8             8.5              0.18         0.30            1.10      0.028   
9             7.2              0.27         0.28           15.20      0.046   
10            6.7              0.30         0.45           10.60      0.032   
11            6.7              0.23         0.31            2.10      0.046   
12            8.6              0.34         0.36            1.40      0.045   
13            7.4              0.20         0.43            7.80      0.045   
14            6.7              0.27         0.26            2.30      0.043   
15            7.1              0.24         0.41           17.80      0.046   
16            6.7              0.25         0.34           12.85      0.048   
17            6.8              0.37         0.51           11.80      0.044   
18            6.5              0.35         0.38            7.40      0.036   
19            6.2              0.35         0.25           18.40      0.051   

    free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                  25.0                 119.0  0.99620  3.15       0.34   
1                  59.0                 196.0  0.99782  3.14       0.40   
2                  40.0                 168.0  0.99760  3.07       0.52   
3                  24.0                 160.0  0.99535  3.17       0.43   
4                  36.0                  86.0  0.99026  2.80       0.55   
5                  30.0                 145.0  0.99470  3.32       0.56   
6                  31.0                 141.0  0.99310  3.16       0.59   
7                  69.0                 219.0  0.99590  3.13       0.40   
8                  34.0                  95.0  0.99272  2.83       0.36   
9                   6.0                  41.0  0.99665  3.17       0.39   
10                 56.0                 212.0  0.99700  3.22       0.59   
11                 30.0                  96.0  0.99260  3.33       0.64   
12                 11.0                 119.0  0.99556  3.17       0.47   
13                 27.0                 153.0  0.99640  3.19       0.55   
14                 61.0                 181.0  0.99394  3.45       0.63   
15                 39.0                 145.0  0.99980  3.32       0.39   
16                 30.0                 161.0  0.99860  3.44       0.47   
17                 62.0                 163.0  0.99760  3.19       0.44   
18                 20.0                 196.0  0.99712  3.47       0.48   
19                 28.0                 182.0  0.99946  3.13       0.62   

    alcohol  quality  
0      10.5        6  
1       8.8        6  
2       9.6        7  
3      10.0        5  
4      12.0        6  
5      11.0        7  
6      11.0        6  
7       8.9        5  
8      10.0        4  
9      10.9        6  
10      9.5        6  
11     10.7        8  
12      9.4        4  
13      9.0        7  
14     10.6        6  
15      8.7        5  
16      9.5        6  
17      8.8        5  
18      9.1        6  
19      9.3        6

In [10]:
wine_df['quality'].value_counts()

6    928
5    570
7    385
8     66
4     40
9      4
3      3
Name: quality, dtype: int64

In [11]:
df2 = wine_df.sort_values('quality', ascending=False)
df2.head(20)

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
1963            6.6              0.36         0.29            1.60      0.021   
1844            7.1              0.26         0.49            2.20      0.032   
116             7.4              0.24         0.36            2.00      0.031   
177             6.9              0.36         0.34            4.20      0.018   
1472            6.1              0.31         0.37            8.40      0.031   
763             5.2              0.24         0.45            3.80      0.027   
157             6.8              0.46         0.26            2.70      0.042   
1253            7.3              0.19         0.27           13.90      0.057   
657             5.6              0.12         0.33            2.90      0.044   
1245            6.4              0.32         0.25            5.00      0.055   
1212            5.2              0.44         0.04            1.40      0.036   
737             6.1              0.28         0.27            4.70      0.030   
1153            7.0              0.36         0.32           10.05      0.045   
759             6.3              0.41         0.18            3.50      0.027   
773             6.2              0.22         0.49            6.00      0.029   
1118            6.8              0.19         0.32            7.05      0.019   
1890            6.8              0.24         0.29            2.00      0.044   
778             6.7              0.28         0.31            7.40      0.041   
781             5.0              0.29         0.54            5.70      0.035   
788             6.8              0.35         0.32            2.40      0.048   
1087            7.1              0.45         0.24            2.70      0.040   
65              5.8              0.28         0.34            2.20      0.037   
1927            6.4              0.22         0.32            7.20      0.028   
1068            6.0              0.26         0.42            5.20      0.027   
1067            7.7              0.35         0.49            8.65      0.033   
1059            6.9              0.15         0.28            4.40      0.029   
1261            7.8              0.18         0.46           12.60      0.042   
180             7.8              0.29         0.36            7.00      0.042   
1936            7.3              0.19         0.27           13.90      0.057   
1682            7.0              0.15         0.38            2.20      0.047   
338             7.1              0.26         0.31            2.20      0.044   
1604            7.0              0.22         0.26            9.20      0.027   
356             7.6              0.20         0.30           14.20      0.056   
363             8.0              0.45         0.36            8.80      0.026   
369             6.6              0.15         0.32            6.00      0.033   
1577            8.1              0.27         0.35            1.70      0.030   
375             7.8              0.29         0.36            7.00      0.042   
387             7.3              0.41         0.29            1.80      0.032   
397             8.0              0.34         0.49            9.00      0.033   
1541            7.3              0.39         0.37            1.10      0.043   
1668            7.3              0.19         0.27           13.90      0.057   
1498            6.7              0.33         0.36            6.60      0.042   
1779            7.0              0.23         0.36            7.10      0.028   
250             6.5              0.18         0.34            1.60      0.040   
1707            7.0              0.24         0.36            2.80      0.034   
480             6.0              0.18         0.31            1.40      0.036   
1734            7.1              0.32         0.34           14.50      0.039   
531             5.6              0.12         0.33            2.90      0.044   
212             7.6              0.20

In [9]:
check_decimals = lambda x: str(x).count('.') <= 1

remove_extra_decimals = wine_df['alcohol'].apply(check_decimals)

wine_df = wine_df[remove_extra_decimals]


In [3]:
X = wine_df.drop("quality", axis=1).values
X

array([[ 7.5 ,  0.33,  0.32, ...,  3.15,  0.34, 10.5 ],
       [ 6.3 ,  0.27,  0.29, ...,  3.14,  0.4 ,  8.8 ],
       [ 7.  ,  0.3 ,  0.51, ...,  3.07,  0.52,  9.6 ],
       ...,
       [ 6.7 ,  0.36,  0.26, ...,  2.99,  0.3 , 12.2 ],
       [ 7.7 ,  0.28,  0.35, ...,  3.27,  0.5 ,  9.6 ],
       [ 5.7 ,  0.22,  0.28, ...,  3.35,  0.38, 12.5 ]])

In [4]:
y = wine_df["quality"].values
y

array([6, 6, 7, ..., 7, 5, 7])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1497, 11)
(499, 11)
(1497,)
(499,)


In [6]:
X_scaler = skl.preprocessing.StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
y_train

array([5, 5, 6, ..., 5, 6, 6])

In [7]:
nn = tf.keras.models.Sequential()
number_input_features = len(X_train[0])

nn.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=number_input_features))
nn.add(tf.keras.layers.Dense(units=22, activation="relu"))
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))
nn.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")


Epoch 1/100
47/47 [==============================] - 0s 677us/step - loss: nan - accuracy: 0.0000e+00
Epoch 2/100
47/47 [==============================] - 0s 626us/step - loss: nan - accuracy: 0.0000e+00
Epoch 3/100
47/47 [==============================] - 0s 647us/step - loss: nan - accuracy: 0.0000e+00
Epoch 4/100
47/47 [==============================] - 0s 635us/step - loss: nan - accuracy: 0.0000e+00
Epoch 5/100
47/47 [==============================] - 0s 608us/step - loss: nan - accuracy: 0.0000e+00
Epoch 6/100
47/47 [==============================] - 0s 646us/step - loss: nan - accuracy: 0.0000e+00
Epoch 7/100
47/47 [==============================] - 0s 638us/step - loss: nan - accuracy: 0.0000e+00
Epoch 8/100
47/47 [==============================] - 0s 639us/step - loss: nan - accuracy: 0.0000e+00
Epoch 9/100
47/47 [==============================] - 0s 631us/step - loss: nan - accuracy: 0.0000e+00
Epoch 10/100
47/47 [==============================] - 0s 613us/step - loss: nan - 

47/47 [==============================] - 0s 632us/step - loss: nan - accuracy: 0.0000e+00
Epoch 81/100
47/47 [==============================] - 0s 631us/step - loss: nan - accuracy: 0.0000e+00
Epoch 82/100
47/47 [==============================] - 0s 611us/step - loss: nan - accuracy: 0.0000e+00
Epoch 83/100
47/47 [==============================] - 0s 591us/step - loss: nan - accuracy: 0.0000e+00
Epoch 84/100
47/47 [==============================] - 0s 632us/step - loss: nan - accuracy: 0.0000e+00
Epoch 85/100
47/47 [==============================] - 0s 594us/step - loss: nan - accuracy: 0.0000e+00
Epoch 86/100
47/47 [==============================] - 0s 604us/step - loss: nan - accuracy: 0.0000e+00
Epoch 87/100
47/47 [==============================] - 0s 620us/step - loss: nan - accuracy: 0.0000e+00
Epoch 88/100
47/47 [==============================] - 0s 593us/step - loss: nan - accuracy: 0.0000e+00
Epoch 89/100
47/47 [==============================] - 0s 607us/step - loss: nan - accu

In [9]:
number_input_features = len(X_train[0])

nn.add(tf.keras.layers.Dense(units=22, activation="relu", input_dim=number_input_features))

In [10]:
nn.add(tf.keras.layers.Dense(units=22, activation="relu"))

In [11]:
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [12]:
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 22)                264       
                                                                 
 dense_1 (Dense)             (None, 22)                506       
                                                                 
 dense_2 (Dense)             (None, 1)                 23        
                                                                 
Total params: 793
Trainable params: 793
Non-trainable params: 0
_________________________________________________________________


In [13]:
nn.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")


Epoch 1/100
47/47 [==============================] - 0s 784us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 2/100
47/47 [==============================] - 0s 732us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 3/100
47/47 [==============================] - 0s 850us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 4/100
47/47 [==============================] - 0s 807us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 5/100
47/47 [==============================] - 0s 818us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 6/100
47/47 [==============================] - 0s 879us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 7/100
47/47 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 8/100
47/47 [==============================] - 0s 944us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 9/100
47/47 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
Epoch 10/100
47/47 [===

In [15]:
# model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
# print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")
